### PR TITLE
Code of Conduct Statement

### PR DESCRIPTION
**Pull request by MXchuck**
### 1st Draft of this statement is looking good.
Pranav has given us a strong start here. I've labelled this Pull Request as a draft to give us some time to look it over - please offer your thoughts here and/or make suggestions in the document, itself.

This addresses issue #70

### CODE REVIEW

**Comment by MXchuck** [comment]
I really like where this work is going and, with a reference to the Student Handbook as Pranav and I discussed, I think it's ready to be formally reviewed.
Please add comments, questions, or further discussion here -or- check off your review if you think it's ready to go.

**Comment by CurryBoy9000** [comment]
I think this is perfect and concise. I am glad that you found a way to create the examples of harassment list for me because I was not sure how to do it.

**Review by CurryBoy9000 — APPROVED** [review]
Like I said in my comment, this is perfect and concise.

**Comment by MXchuck** [comment]
> I think this is perfect and concise. I am glad that you found a way to create the examples of harassment list for me because I was not sure how to do it.

No, you did it correctly - I just tightened up the indenting.

**Review by MXSophia — APPROVED** [review]

**Review by AaravMehta4897 — COMMENTED** [review]
Looks great!

**Pull request merged**
